spring:
  application:
    name: eurakeserver
server:
              #注册服务端口
              port: 7002
eureka:
  client:
    serviceUrl:
      defaultZone: http://node1:7001/eureka/,http://node3:7003/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: node2
    preferIpAddress: false