spring:
  application:
    name: api-gatway
server:
  port: 4000
#配置eureka服务地址
eureka:
  client:
    service-url:
      defaultZone: http://node1:7001/eureka/,http://node2:7002/eureka/,http://node3:7003/eureka/
  #instance:
   # prefer-ip-address: true
zuul:
  host:
     #zuul配置
    max-per-route-connections: 50
    max-total-connections: 200
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  #关闭重试机制
  retryable: true
  routes:
    service-a:
      #说明: path不是微服务的地址而是自己定义的地址如果微服务地址为 /api/product 则此处访问地址为: /product/api/product
      path: /service-a/**
      serviceId: service-a
  include-debug-header: true
#开启debug模式
#debug: true