spring:
  application:
    name: discovery-learn

server:
  port: 5002

# 服务注册中心
eureka:
  client:
    serviceUrl:
       defaultZone: http://node1:7001/eureka/,http://node2:7002/eureka/,http://node3:7003/eureka/